name: Test
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - run: corepack enable
      - run: npm i
      - name: Test
        run: npm run verify:android
